config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations =>
                                          "registrations", :confirmations => "confirmations", :sessions =>
                                          "sessions"}
  authenticated :user do
    root :to => 'homes#index', :as => :authenticated_root
  end
  root :to => redirect('/users/sign_in')

  resources :homes do

  end
  resources :roles
  resources :user_roles
  resources :functions
  resources :functions_roles

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
   #   if user && user.persisted? && user.active
   #  user.functions.each do |function|
   #
   #      can function.action.to_sym, function.object.camelize.constantize
   #
   #   end
   #   if user.roles.where('role_name = "Admin"').size >0
   #
   #   can :manage , :all
   #
   #   end
   #
   #
   # end
    # can :manage , :home
    can :manage , :session
    can :manage , :registration






    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/function.rb
class Function < ActiveRecord::Base
  has_many :functions_roleses, dependent: :destroy
end

app/models/functions_roles.rb
class FunctionsRoles < ActiveRecord::Base
  belongs_to :role
  belongs_to :function
end

app/models/role.rb
class Role < ActiveRecord::Base
has_many :user_roleses, dependent: :destroy
has_many :functions_roleses, dependent: :destroy
has_many :functions, through: :functions_roleses
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_roleses, dependent: :destroy
  has_many :roles, through: :user_roleses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_roles.rb
class UserRoles < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  # authorize_resource
  include ActionController::MimeResponds
  include ApplicationHelper



  # layout :layout_by_resource
  protected
  def layout_by_resource
    if devise_controller?
      if resource_name == :admin
        "devise_admin_application" #admin model will use this layout
      elsif resource_name == :employee
        "devise_employee_application" #employee model will use this
        layout
      else
        "devise_application" #other devise model will use this layout
      end
    else
      "application" #default rails application layout
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :phone, :condo_id, :full_name, :address, :password, :password_confirmation, :remember_me) }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout 'blank'
  def create
    build_resource(sign_up_params)
    resource_saved = resource.save
    yield resource if block_given?
    respond_to do |format|
      if resource_saved
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          format.html { respond_with resource, location:  after_sign_in_path(user)}#after_sign_up_path_for(resource)
          format.js {}
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          format.html { respond_with resource, location: after_inactive_sign_up_path_for(resource) }
          format.js {}
        end
      else
        clean_up_passwords resource
        format.html { respond_with resource }
        format.js {}
      end

    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout 'blank'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/homes/index.html.erb
this is index page!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Daily Spending</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'fav.png' %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container">
  <div id="notifications"></div>

  <div class="row padding-20-px">
    <div class="col-lg-12">
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/homes">Daily Spending</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/homes">Home</a></li>
              <li><a href="">Spending Management</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Hi! ' + current_user.full_name %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
          <!--/.nav-collapse -->
        </div>
      </div>
    </div>
  </div>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= msg %>
      <% end %>
  <% end %>

  <div>
    <%= yield %>
  </div>

  <div class="row">
    <div class="footer">
      <p>© Innoria Company - Project Daily Spending v26082014 - Copyright: Dương Hồng Khanh</p>
    </div>
  </div>
</div>


<div class="modal fade" id="app-Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Error</h4>
      </div>
      <div class="modal-body">
        <div>
          <h3>The change you wanted was rejected.</h3>

          <p>Maybe you tried to change something you didn't have access to.</p>
        </div>
        <p>If you are the application owner check the logs for more information.</p>


      </div>

      <div class="modal-footer">
        <div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>


        </div>
      </div>


    </div>
  </div>
</div>
</body>
</html>

<script>

    function setLanguage(val) {
        $.post('/homes/setLanguage', {val: val}, function () {
            location.reload(true);
        });
    }
</script>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Resident Management System</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>